# Generated by Django 4.1 on 2022-08-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peticao',
            name='category',
            field=models.CharField(default='Previdenciário', max_length=40),
        ),
        migrations.AddField(
            model_name='peticao',
            name='description',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
